Repository ISEGYE-Universe/frontend, pull requests merged in 2023-11, with the labels that each got.

#16 feat/chart-page: ✨ 차트 페이지 좌측 영역 마크업
  public/images/icon/ad-right-chevron.svg
  public/images/icon/chart-down-icon.svg
  public/images/icon/chart-up-icon.svg
  public/images/icon/chart-zero-icon.svg
  src/components/Chart/AlbumNewsCard.tsx
  src/components/Chart/ArticleADBanner.tsx
  src/components/Chart/ChartLeftSection.tsx
  src/components/Chart/ChartMusicCard.tsx
  src/components/Chart/ChartRightSection.tsx
  src/components/Chart/HRLine.tsx
  src/components/Chart/SubTitle.tsx
  src/components/Chart/TimeBaseSubTitle.tsx
  src/components/Chart/Title.tsx
  src/components/Chart/Top100Chart.tsx
  src/data/chart.json
  src/pages/chart/index.tsx
  src/styles/Global.tsx
Labels: enhancement

#24 Feat/main news: 메인 페이지 뉴스 컴포넌트
  package-lock.json
  public/images/icon/KakaoPageIcon.svg
  public/images/icon/KakaoWebtoonIcon.svg
  public/images/icon/NewsHeaderButtonArrow.svg
  public/images/icon/banner-button-left-arrow.svg
  public/images/icon/banner-button-right-arrow.svg
  src/components/News/News.tsx
  src/components/News/NewsHeaderButton.tsx
  src/components/News/NewsHeaderButtonList.tsx
  src/components/News/NewsThumnail.tsx
  src/components/News/NewsThumnailList.tsx
  src/styles/Global.tsx
  yarn.lock
Labels: enhancement

#22 fix/font: :bug: 말줄임표 정렬 이슈 관련 css 수정 작업 (#20)
  src/styles/Global.tsx
Labels: bug

#23 Feat/font: 💄 폰트 자간 추가
  src/styles/Font.ts
Labels: enhancement

#20 Feat/main artist: 메인 페이지 - 아티스트 컴포넌트
  public/images/main-artist/르르땅_바탕화면_1.png
  public/images/main-artist/릴파땅_바탕화면_1.png
  public/images/main-artist/맴버프로필=GOSEGU.png
  public/images/main-artist/맴버프로필=INE.png
  public/images/main-artist/맴버프로필=JINGBURGER.png
  public/images/main-artist/맴버프로필=JURURU.png
  public/images/main-artist/맴버프로필=LILPA.png
  public/images/main-artist/맴버프로필=VIICHAN.png
  public/images/main-artist/버거땅_바탕화면_1.png
  public/images/main-artist/세구땅_바탕화면_1.png
  public/images/main-artist/이네땅_바탕화면_1.png
  public/images/main-artist/챠니_바탕화면_1.png
  src/components/Artist/Artist.tsx
  src/components/Artist/ArtistMainScreen.tsx
  src/components/Artist/ArtistMainScreenToggleButton.tsx
  src/components/Artist/ArtistMainScreenToggleButtonList.tsx
  src/components/News/color.ts
  src/pages/index.tsx
  yarn.lock
Labels: enhancement

#54 Chore/eslint: prefer-default-export, require-default-props 옵션 off
  .eslintrc.json
Labels: enhancement

#59 Chore/eslint: react/jsx-props-no-spreading 예외 룰 추가
  .eslintrc.json
Labels: chore

#47 [FIX] 메인 페이지 Artist 섹션 ESLint 에 맞춰서 수정
  src/components/Artist/ArtistMainScreenToggleButton.tsx
Labels: bug fix

#49 [FIX] 메인 페이지 News 섹션 ESLint fix
  src/components/News/NewsHeader.tsx
  src/components/News/NewsHeaderButton.tsx
  src/components/News/NewsThumnail.tsx
  src/components/News/NewsThumnailList.tsx
  src/components/News/NewsWeeklyEventBanner.tsx
  src/components/News/color.ts
Labels: feature
