Repository ISEGYE-Universe/frontend, pull requests merged in 2023-12, with the labels that each got.

#64 Fix/movie-eslint: lint 오류 해결
  src/components/Movie/MovieSlider.tsx
  src/components/Movie/svg/LeftArrow.tsx
  src/components/Movie/svg/RightArrow.tsx
  src/components/Movie/svg/index.ts
Labels: bug fix

#57 feat/chart-page: 레이아웃(최근 명예의 전당 + 역대 기록 영역 + Top100 차트) + eslint fix
  package.json
  public/images/chart/history-another-world.jpg
  public/images/chart/history-isegye-fesitval.jpg
  public/images/chart/history-kidding.jpg
  public/images/chart/history-lockdown.jpg
  src/components/Chart/AlbumNewsCard.tsx
  src/components/Chart/ArticleADBanner.tsx
  src/components/Chart/ChartMusicCard.tsx
  src/components/Chart/EmblaHistoryButton.tsx
  src/components/Chart/HRLine.tsx
  src/components/Chart/HallOfFame.tsx
  src/components/Chart/HistoryCard.tsx
  src/components/Chart/HistoryCarousel.tsx
  src/components/Chart/MelonInfo.tsx
  src/components/Chart/RoundedLinkButton.tsx
  src/components/Chart/SubTitle.tsx
  src/components/Chart/TimeBaseSubTitle.tsx
  src/components/Chart/Title.tsx
  src/components/Chart/Top100Chart.tsx
  src/components/Chart/Top100ChartSwitch.tsx
  src/components/Chart/Top100Section.tsx
  src/components/Chart/WeeklyAward.tsx
  src/data/chart.json
  src/pages/chart/index.tsx
  src/styles/ChartColor.ts
  yarn.lock
Labels: bug fix, feature

#66 :rotating_light: fix: layout 측 lint 픽스
  src/components/CommonLayout/Navbar.tsx
  src/components/CommonLayout/Navbar/SubNav.tsx
  src/components/layout.tsx
Labels: bug fix

#67 Fix/chart-eslint: eslint warning 해결
  src/components/Chart/WeeklyAward.tsx
Labels: bug fix

#61 :lipstick: feat/global-css: reset css - p, button, a
  src/styles/Global.tsx
Labels: feature

#63 ✨ feat/member-profile: 기본 레이아웃 틀 구현
  public/images/member-profile/jururu/bg-calendar.png
  public/images/member-profile/jururu/top-banner.png
  src/@type/index.d.ts
  src/components/MemberProfile/MemberProfileCoverSong.tsx
  src/components/MemberProfile/MemberProfileSchedule.tsx
  src/components/MemberProfile/MemberProfileTopBanner.tsx
  src/components/MemberProfile/MemberProfileWakscord.tsx
  src/components/MemberProfile/MemberProfileYoutube.tsx
  src/data/member-profile.json
  src/pages/member-profile/[memberName].tsx
  src/styles/MemberProfileColor.ts
Labels: feature

#73 Feat/member-profile: 상단 배너 레이아웃 구현
  public/images/member-profile/jururu/profile.png
  src/components/MemberProfile/MemberProfileTopBanner.css.ts
  src/components/MemberProfile/MemberProfileTopBanner.tsx
  src/components/MemberProfile/MemberProfileYoutube.tsx
  src/pages/member-profile/[memberName].tsx
  src/styles/MemberProfileColor.ts
Labels: feature

#75 Fix/member-profile: dynamic routing 이슈
  src/pages/member-profile/[memberName].tsx
Labels: bug fix

#78 Feat/member-profile: 커버곡 영역 레이아웃
  public/images/member-profile/gosegu/icon-play.svg
  public/images/member-profile/gosegu/signature.png
  public/images/member-profile/ine/icon-play.svg
  public/images/member-profile/ine/signature.png
  public/images/member-profile/jingburger/icon-play.svg
  public/images/member-profile/jingburger/signature.png
  public/images/member-profile/jururu/icon-play.svg
  public/images/member-profile/jururu/signature.png
  public/images/member-profile/lilpa/icon-play.svg
  public/images/member-profile/lilpa/signature.png
  public/images/member-profile/viichan/icon-play.svg
  public/images/member-profile/viichan/signature.png
  src/components/MemberProfile/MemberProfileCoverSong.css.ts
  src/components/MemberProfile/MemberProfileCoverSong.tsx
  src/data/member-profile.json
  src/pages/member-profile/[memberName].tsx
  src/styles/MemberProfileColor.ts
Labels: feature

#79 Feat/member-profile: Youtube 영역 레이아웃 구현
  public/images/.gitkeep
  public/images/icon/icon-yt-black.svg
  src/components/MemberProfile/MemberProfileTitle.tsx
  src/components/MemberProfile/MemberProfileYoutube.tsx
  src/data/.gitkeep
  src/data/member-profile.json
  src/pages/member-profile/[memberName].tsx
  src/styles/MemberProfileColor.ts
Labels: feature

#81 Refactor/main news: NEWS 섹션 디자인 최신화
  public/images/icon/KakaoPageIcon.svg
  public/images/icon/KakaoWebtoonIcon.svg
  public/images/icon/NewsHeaderButtonArrow.svg
  src/components/News/News.tsx
  src/components/News/NewsHeader.tsx
  src/components/News/NewsHeaderButton.tsx
  src/components/News/NewsHeaderButtonList.tsx
Labels: refactor

#82 Feat/member-profile: 캘린더 영역 레이아웃 구현
  package.json
  public/images/icon/member-profile/keyboard-arrow-down.svg
  public/images/icon/member-profile/keyboard-arrow-left.svg
  public/images/icon/member-profile/keyboard-arrow-right.svg
  public/images/icon/member-profile/keyboard-arrow-up.svg
  src/@type/index.d.ts
  src/components/MemberProfile/MemberProfileCalendar.css.ts
  src/components/MemberProfile/MemberProfileCalendar.tsx
  src/components/MemberProfile/MemberProfileCalendarStreamList.css.ts
  src/components/MemberProfile/MemberProfileCalendarStreamList.tsx
  src/components/MemberProfile/MemberProfileCoverSong.tsx
  src/components/MemberProfile/MemberProfileSchedule.css.ts
  src/components/MemberProfile/MemberProfileSchedule.tsx
  src/components/MemberProfile/MemberProfileTopBanner.tsx
  src/components/MemberProfile/MemberProfileWakscord.tsx
  src/components/MemberProfile/MemberProfileYoutube.tsx
  src/data/member-profile.json
  src/pages/member-profile/MemberProfile.css.ts
  src/pages/member-profile/[memberName].tsx
  src/styles/MemberProfileColor.ts
  yarn.lock
Labels: feature

#83 Refactor/main artist: ARTIST 섹션 디자인 최신화
  public/images/main-artist/르르땅_바탕화면_1.png
  public/images/main-artist/릴파땅_바탕화면_1.png
  public/images/main-artist/버거땅_바탕화면_1.png
  public/images/main-artist/세구땅_바탕화면_1.png
  public/images/main-artist/이네땅_바탕화면_1.png
  public/images/main-artist/챠니_바탕화면_1.png
  src/components/Artist/Artist.tsx
  src/components/Artist/ArtistMainScreen.tsx
  src/components/Artist/ArtistMainScreenToggleButton.tsx
  src/components/Artist/ArtistMainScreenToggleButtonList.tsx
Labels: refactor

#86 Refactor/main artist: ARTIST 섹션 데이터 JSON화
  src/components/Artist/Artist.tsx
  src/components/Artist/ArtistMainScreen.tsx
  src/components/Artist/ArtistMainScreenToggleButton.tsx
  src/components/Artist/ArtistMainScreenToggleButtonList.tsx
  src/data/main-artist/artist-wallpaper.json
  src/data/main-artist/button-icon.json
Labels: refactor

#90 Fix/chart page: "line" is not a registered controller 오류 해결
  src/components/Chart/Top100Chart.tsx
  src/components/MemberProfile/MemberProfile.css.ts
  src/components/MemberProfile/MemberProfileSchedule.tsx
  src/pages/member-profile/[memberName].tsx
Labels: bug fix

#91 Fix/lint
  src/components/CommonLayout/Footer/Text.tsx
Labels: bug fix

#92 Fix/member-profile-calendar: 멤버 프로필 스케줄 > 달력 영역 highlight 스타일링 로직 개선
  src/components/MemberProfile/MemberProfileCalendar.css.ts
  src/components/MemberProfile/MemberProfileCalendar.tsx
Labels: bug fix

#97 Refactor/main news > 데이터 JSON 화 + 이미지 적용
  public/images/icon/banner-button-left-arrow.svg
  public/images/icon/banner-button-right-arrow.svg
  public/images/main-news/main-event-1.png
  public/images/main-news/main-event-2.png
  public/images/main-news/main-event-3.png
  public/images/main-news/weekly-event-1.png
  public/images/main-news/weekly-event-2.png
  public/images/main-news/weekly-event-3.png
  public/images/main-news/weekly-event-4.png
  public/images/main-news/weekly-event-5.png
  src/components/News/NewsThumnailList.tsx
  src/components/News/NewsWeeklyEventBanner.tsx
  src/components/News/NewsWeeklyEventBannerList.tsx
  src/data/main-news/main-event-banner.json
  src/data/main-news/weekly-event-banner.json
Labels: refactor

#89 Feat/member-profile: 왁스코드 영역 레이아웃 구현
  public/images/icon/icon-refresh.svg
  public/images/member-profile/logo-wakscord.png
  src/components/Albums/AlbumBtn.tsx
  src/components/MemberProfile/MemberProfileCalendarStreamList.tsx
  src/components/MemberProfile/MemberProfileTitle.tsx
  src/components/MemberProfile/MemberProfileTopBanner.tsx
  src/components/MemberProfile/MemberProfileWakscord.css.ts
  src/components/MemberProfile/MemberProfileWakscord.tsx
  src/components/MemberProfile/MemberProfileYoutube.tsx
  src/styles/MemberProfileColor.ts
Labels: feature

#96 Refactor/main movie 추가사항 변경
  src/components/Movie/MovieSlider.tsx
  src/components/Movie/style/Movie.Style.ts
Labels: enhancement

#99 Feat: chart-page: 차트 페이지 날짜 클릭 시 좌측 일정 하이라이팅 + 빌드 오류 해결
  src/components/MemberProfile/MemberProfile.css.ts
  src/components/MemberProfile/MemberProfileCalendar.css.ts
  src/components/MemberProfile/MemberProfileCalendar.tsx
  src/components/MemberProfile/MemberProfileCalendarStreamList.css.ts
  src/components/MemberProfile/MemberProfileTopBanner.tsx
Labels: bug fix, enhancement

#103 Feat/member-profile: 플레이어 위젯 레이아웃 구현
  src/components/MemberProfile/MemberProfile.css.ts
  src/components/MemberProfile/MemberProfileCalendar.tsx
  src/components/MemberProfile/MemberProfileCoverSong.tsx
  src/components/MemberProfile/MemberProfilePlayerWidget.css.ts
  src/components/MemberProfile/MemberProfilePlayerWidget.tsx
  src/components/MemberProfile/MemberProfileSchedule.tsx
  src/components/MemberProfile/MemberProfileTopBanner.tsx
  src/components/MemberProfile/WidgetPlayerIcon.tsx
  src/pages/member-profile/[memberName].tsx
  src/store/MemberProfile/MemberProfileStore.ts
Labels: feature

#98 Feat/chart-page: 차트 영역 visx로 변경하여 구현, 가장 최근 데이터 말풍선 추가
  package.json
  src/components/Chart/HistoryCarousel.tsx
  src/components/Chart/Top100Chart.css.ts
  src/components/Chart/Top100Chart.tsx
  src/components/Chart/Top100Section.tsx
  yarn.lock
Labels: enhancement

#104 Feat/profile-page: 프로필 페이지 다이나믹 라우팅 적용
  src/components/Profile/ProfileIntroductionBox.tsx
  src/data/profile.json
  src/pages/profile/[memberName].tsx
  src/pages/profile/gosegu.tsx
  src/pages/profile/ine.tsx
  src/pages/profile/jingburger.tsx
  src/pages/profile/jururu.tsx
  src/pages/profile/lilpa.tsx
  src/pages/profile/viichan.tsx
Labels: refactor, enhancement

#107 Fix/footer: 모달 비활성화 시에도 영역이 화면을 가리는 문제 해결
  src/components/CommonLayout/Footer/CreatorModal.tsx
Labels: bug fix

#108 Feat/font: 폰트의 기본 line-height 지정
  src/components/Albums/AlbumDetail.tsx
  src/components/Chart/AlbumNewsCard.tsx
  src/components/Chart/ArticleADBanner.tsx
  src/components/Chart/ChartMusicCard.tsx
  src/components/Chart/HallOfFame.tsx
  src/components/Chart/HistoryCard.tsx
  src/components/Chart/MelonInfo.tsx
  src/components/Chart/RoundedLinkButton.tsx
  src/components/Chart/SubTitle.tsx
  src/components/Chart/Title.tsx
  src/components/Chart/Top100Chart.css.ts
  src/components/Chart/Top100Section.tsx
  src/components/Chart/WeeklyAward.tsx
  src/components/MemberProfile/MemberProfileCalendar.css.ts
  src/components/MemberProfile/MemberProfileCalendarStreamList.css.ts
  src/components/MemberProfile/MemberProfileCoverSong.css.ts
  src/components/MemberProfile/MemberProfileTitle.tsx
  src/components/MemberProfile/MemberProfileTopBanner.css.ts
  src/components/MemberProfile/MemberProfileWakscord.css.ts
  src/components/MemberProfile/MemberProfileYoutube.tsx
  src/styles/Font.ts
Labels: refactor, enhancement
